// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadastroCliente.Data;

namespace cadastroCliente.Migrations
{
    [DbContext(typeof(cadastroClienteContext))]
    [Migration("20220919220253_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cadastroCliente.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("altura")
                        .HasColumnType("float");

                    b.Property<double>("comprimento")
                        .HasColumnType("float");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("largura")
                        .HasColumnType("float");

                    b.Property<double>("valorCompra")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("cadastroCliente.Models.cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cep")
                        .HasColumnType("int");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cpf")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("estadoCivilId")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rg")
                        .HasColumnType("int");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.HasKey("clienteId");

                    b.HasIndex("estadoCivilId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("cadastroCliente.Models.estadoCivil", b =>
                {
                    b.Property<int>("estadoCivilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("casado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("divorciado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("solteiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("viuvo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("estadoCivilId");

                    b.ToTable("estadoCivils");
                });

            modelBuilder.Entity("cadastroCliente.Models.cliente", b =>
                {
                    b.HasOne("cadastroCliente.Models.estadoCivil", "estadoCivil")
                        .WithMany()
                        .HasForeignKey("estadoCivilId");

                    b.Navigation("estadoCivil");
                });
#pragma warning restore 612, 618
        }
    }
}
